package: ycom_impersonate
version: '0.0.1'
author: 'Friends Of REDAXO'
supportpage: https://github.com/FriendsOfREDAXO/ycom_impersonate
requires:
    redaxo: '^5.13.0'
    php:
        version: '>=7.3, <9'
